### ISSUE TITLE
Todo - Meeting 1/31/2023

### ISSUE THREAD

**Issue by YurkoWasHere** [starlinglab/archive-explorer#18]
Update Hashes- PR #25 
- [x] Encrypted Archive 
  - [x] CID
  - [x] SHA256
- [x] Archive 
  - [x] CID
  - [x] SHA256
---
- [x] use "Archive Explorer Version" - Instead of Published #21
- [x] Add public and private to all (even if its empty) - PR #26 
- [x] Add multiple root of trusts when they exist - PR #23 
- [x] Click icon next to each root of trust showing only that signature
